project_name: finetuning
random_state: 2022
lr: 5.0e-4
batch_size: 32
test_batch_size: 32
num_workers: 8
n_epochs: 40
weight_decay: 1.0e-4
label_smoothing: 0.0
optimizer: adamw
lr_scheduler: cosineannealing

imbalanced: true

# =========================== MODEL =====================
model_name: "efficientnet_b0"
input_size: 256
test_input_size: 256
#model_ckpt: outputs/2022-12-04_19-01-09_efficientnet_b0/E0003_0.10102276654182164.pth
model_ckpt: null
drop_rate: 0
